# Generated by Django 5.2.7 on 2025-10-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='order',
            new_name='cart',
        ),
    ]
