# Generated by Django 5.2.7 on 2025-10-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_order_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercart',
            name='order_date',
        ),
    ]
